execute @e[type=dragonmounts:fire_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ ice 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 ice 0 function egg/iceegg

execute @e[type=dragonmounts:ender_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ ice 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 ice 0 function egg/iceegg

execute @e[type=dragonmounts:aether_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ ice 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 ice 0 function egg/iceegg

execute @e[type=dragonmounts:forest_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ ice 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 ice 0 function egg/iceegg

execute @e[type=dragonmounts:nether_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ ice 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 ice 0 function egg/iceegg

execute @e[type=dragonmounts:water_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ ice 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 ice 0 function egg/iceegg

execute @e[type=dragonmounts:skeleton_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ ice 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 ice 0 function egg/iceegg


execute @e[type=dragonmounts:fire_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ oak_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 oak_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 oak_log 0 function egg/forestegg

execute @e[type=dragonmounts:ice_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ oak_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 oak_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 oak_log 0 function egg/forestegg

execute @e[type=dragonmounts:water_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ oak_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 oak_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 oak_log 0 function egg/forestegg

execute @e[type=dragonmounts:aether_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ oak_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 oak_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 oak_log 0 function egg/forestegg

execute @e[type=dragonmounts:ender_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ oak_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 oak_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 oak_log 0 function egg/forestegg

execute @e[type=dragonmounts:skeleton_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ oak_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 oak_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 oak_log 0 function egg/forestegg


execute @e[type=dragonmounts:nether_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ oak_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 oak_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 oak_log 0 function egg/forestegg



execute @e[type=dragonmounts:fire_dragon_egg,scores={Timer=6000}] ~~~ detect  ~ ~-1 ~ glowstone 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ glowstone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ glowstone 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 glowstone 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 glowstone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 glowstone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 glowstone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 glowstone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 glowstone 0 function egg/aetheregg

execute @e[type=dragonmounts:forest_dragon_egg,scores={Timer=6000}] ~~~ detect  ~ ~-1 ~ glowstone 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ glowstone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ glowstone 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 glowstone 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 glowstone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 glowstone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 glowstone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 glowstone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 glowstone 0 function egg/aetheregg

execute @e[type=dragonmounts:nether_dragon_egg,scores={Timer=6000}] ~~~ detect  ~ ~-1 ~ glowstone 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ glowstone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ glowstone 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 glowstone 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 glowstone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 glowstone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 glowstone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 glowstone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 glowstone 0 function egg/aetheregg

execute @e[type=dragonmounts:water_dragon_egg,scores={Timer=6000}] ~~~ detect  ~ ~-1 ~ glowstone 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ glowstone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ glowstone 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 glowstone 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 glowstone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 glowstone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 glowstone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 glowstone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 glowstone 0 function egg/aetheregg

execute @e[type=dragonmounts:ice_dragon_egg,scores={Timer=6000}] ~~~ detect  ~ ~-1 ~ glowstone 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ glowstone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ glowstone 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 glowstone 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 glowstone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 glowstone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 glowstone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 glowstone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 glowstone 0 function egg/aetheregg

execute @e[type=dragonmounts:skeleton_dragon_egg,scores={Timer=6000}] ~~~ detect  ~ ~-1 ~ glowstone 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ glowstone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ glowstone 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 glowstone 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 glowstone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 glowstone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 glowstone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 glowstone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 glowstone 0 function egg/aetheregg

execute @e[type=dragonmounts:ender_dragon_egg,scores={Timer=6000}] ~~~ detect  ~ ~-1 ~ glowstone 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ glowstone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ glowstone 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 glowstone 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 glowstone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 glowstone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 glowstone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 glowstone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 glowstone 0 function egg/aetheregg



execute @e[type=dragonmounts:fire_dragon_egg,scores={Timer=6000}] ~~~ detect  ~1 ~-1 ~ minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:water 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:water 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:water 0 function egg/wateregg 

execute @e[type=dragonmounts:ice_dragon_egg,scores={Timer=6000}] ~~~ detect  ~1 ~-1 ~ minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:water 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:water 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:water 0 function egg/wateregg

execute @e[type=dragonmounts:forest_dragon_egg,scores={Timer=6000}] ~~~ detect  ~1 ~-1 ~ minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:water 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:water 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:water 0 function egg/wateregg

execute @e[type=dragonmounts:ender_dragon_egg,scores={Timer=6000}] ~~~ detect  ~1 ~-1 ~ minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:water 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:water 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:water 0 function egg/wateregg

execute @e[type=dragonmounts:nether_dragon_egg,scores={Timer=6000}] ~~~ detect  ~1 ~-1 ~ minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:water 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:water 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:water 0 function egg/wateregg

execute @e[type=dragonmounts:aether_dragon_egg,scores={Timer=6000}] ~~~ detect  ~1 ~-1 ~ minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:water 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:water 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:water 0 function egg/wateregg

execute @e[type=dragonmounts:skeleton_dragon_egg,scores={Timer=6000}] ~~~ detect  ~1 ~-1 ~ minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:water 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:water 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:water 0 function egg/wateregg



execute @e[type=dragonmounts:fire_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ magma 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ magma 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ magma 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 magma 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 magma 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 magma 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 magma 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 magma 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 magma 0 function egg/netheregg

execute @e[type=dragonmounts:water_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ magma 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ magma 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ magma 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 magma 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 magma 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 magma 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 magma 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 magma 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 magma 0 function egg/netheregg

execute @e[type=dragonmounts:aether_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ magma 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ magma 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ magma 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 magma 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 magma 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 magma 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 magma 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 magma 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 magma 0 function egg/netheregg

execute @e[type=dragonmounts:ender_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ magma 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ magma 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ magma 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 magma 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 magma 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 magma 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 magma 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 magma 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 magma 0 function egg/netheregg

execute @e[type=dragonmounts:ice_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ magma 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ magma 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ magma 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 magma 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 magma 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 magma 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 magma 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 magma 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 magma 0 function egg/netheregg

execute @e[type=dragonmounts:skeleton_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ magma 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ magma 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ magma 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 magma 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 magma 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 magma 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 magma 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 magma 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 magma 0 function egg/netheregg

execute @e[type=dragonmounts:forest_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ magma 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ magma 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ magma 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 magma 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 magma 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 magma 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 magma 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 magma 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 magma 0 function egg/netheregg



execute @e[type=dragonmounts:fire_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ bone_block 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 bone_block 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 bone_block 0 function egg/skeletonegg

execute @e[type=dragonmounts:ice_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ bone_block 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 bone_block 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 bone_block 0 function egg/skeletonegg

execute @e[type=dragonmounts:nether_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ bone_block 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 bone_block 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 bone_block 0 function egg/skeletonegg

execute @e[type=dragonmounts:aether_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ bone_block 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 bone_block 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 bone_block 0 function egg/skeletonegg

execute @e[type=dragonmounts:ender_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ bone_block 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 bone_block 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 bone_block 0 function egg/skeletonegg

execute @e[type=dragonmounts:forest_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ bone_block 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 bone_block 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 bone_block 0 function egg/skeletonegg

execute @e[type=dragonmounts:water_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ bone_block 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 bone_block 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 bone_block 0 function egg/skeletonegg



execute @e[type=dragonmounts:ice_dragon_egg,scores={Timer=6000}] ~~~ detect ~1 ~-1 ~ minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:lava 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:lava 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:lava 0 function egg/fireegg

execute @e[type=dragonmounts:water_dragon_egg,scores={Timer=6000}] ~~~ detect ~1 ~-1 ~ minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:lava 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:lava 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:lava 0 function egg/fireegg

execute @e[type=dragonmounts:forest_dragon_egg,scores={Timer=6000}] ~~~ detect ~1 ~-1 ~ minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:lava 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:lava 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:lava 0 function egg/fireegg

execute @e[type=dragonmounts:skeleton_dragon_egg,scores={Timer=6000}] ~~~ detect ~1 ~-1 ~ minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:lava 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:lava 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:lava 0 function egg/fireegg

execute @e[type=dragonmounts:aether_dragon_egg,scores={Timer=6000}] ~~~ detect ~1 ~-1 ~ minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:lava 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:lava 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:lava 0 function egg/fireegg

execute @e[type=dragonmounts:nether_dragon_egg,scores={Timer=6000}] ~~~ detect ~1 ~-1 ~ minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:lava 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:lava 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:lava 0 function egg/fireegg

execute @e[type=dragonmounts:ender_dragon_egg,scores={Timer=6000}] ~~~ detect ~1 ~-1 ~ minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:lava 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:lava 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:lava 0 function egg/fireegg

execute @e[type=dragonmounts:ice_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ end_stone 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ end_stone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ end_stone 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 end_stone 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 end_stone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 end_stone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 end_stone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 end_stone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 end_stone 0 function egg/enderegg

execute @e[type=dragonmounts:fire_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ end_stone 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ end_stone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ end_stone 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 end_stone 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 end_stone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 end_stone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 end_stone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 end_stone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 end_stone 0 function egg/enderegg

execute @e[type=dragonmounts:aether_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ end_stone 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ end_stone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ end_stone 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 end_stone 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 end_stone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 end_stone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 end_stone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 end_stone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 end_stone 0 function egg/enderegg

execute @e[type=dragonmounts:nether_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ end_stone 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ end_stone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ end_stone 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 end_stone 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 end_stone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 end_stone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 end_stone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 end_stone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 end_stone 0 function egg/enderegg

execute @e[type=dragonmounts:forest_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ end_stone 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ end_stone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ end_stone 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 end_stone 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 end_stone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 end_stone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 end_stone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 end_stone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 end_stone 0 function egg/enderegg

execute @e[type=dragonmounts:water_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ end_stone 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ end_stone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ end_stone 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 end_stone 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 end_stone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 end_stone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 end_stone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 end_stone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 end_stone 0 function egg/enderegg

execute @e[type=dragonmounts:skeleton_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ end_stone 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ end_stone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ end_stone 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 end_stone 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 end_stone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 end_stone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 end_stone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 end_stone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 end_stone 0 function egg/enderegg

execute @e[type=dragonmounts:fire_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ snow 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ snow 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 snow 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 snow 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 snow 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 snow 0 function egg/iceegg

execute @e[type=dragonmounts:ender_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ snow 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ snow 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 snow 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 snow 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 snow 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 snow 0 function egg/iceegg

execute @e[type=dragonmounts:aether_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ snow 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ snow 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 snow 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 snow 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 snow 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 snow 0 function egg/iceegg

execute @e[type=dragonmounts:forest_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ snow 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ snow 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 snow 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 snow 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 snow 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 snow 0 function egg/iceegg

execute @e[type=dragonmounts:nether_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ snow 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ snow 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 snow 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 snow 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 snow 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 snow 0 function egg/iceegg

execute @e[type=dragonmounts:water_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ snow 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ snow 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 snow 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 snow 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 snow 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 snow 0 function egg/iceegg

execute @e[type=dragonmounts:skeleton_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ snow 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ snow 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 snow 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 snow 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 snow 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 snow 0 function egg/iceegg